name: Release Candidate Workflow

on:
  push:
    branches:
      - main
      - releases/**

jobs:
  workspace-check:

  dashboard-build-and-draft:
    uses: ./.github/workflows/dashboard-build-and-draft.yml
    with:
      debug: false
      version: null
    secrets: inherit

  core-build-and-draft:
    uses: ./.github/workflows/core-build-and-draft.yml
    with:
      version: null
    secrets: inherit
