name: Core - Clippy Check

on:
  workflow_dispatch:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  core-clippy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Eeee
        run: echo "Finished"
