name: Core - Clippy Check

on:
  workflow_dispatch:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  core-clippy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: false

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: rust-cache
          shared-key: workspace-x86_64-unknown-linux-gnu-release-check

      - name: Run Clippy Check
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --release
