name: Dashboard - Build and Draft Frontend

on:
  workflow_dispatch:
  workflow_call:

jobs:
  dashboard-build-tauri-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: ./dashboard/package-lock.json

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: ./dashboard

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install Tauri dependencies
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          source $HOME/.cargo/env
          cargo install tauri-cli

      - name: Build the Tauri app
        run: |
          source $HOME/.cargo/env
          npm run tauri build
        working-directory: ./dashboard

      - name: Archive Tauri app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tauri-app-artifacts
          path: ./dashboard/target/release/*

